### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by Saladino** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#235] opened 2021-07-26 14:40 UTC
**Describe the bug**
Any command configured in the sttings "Commands" section is not working. No custom commands (tested with /help) or predefined ones work. Changing the hotkey to something else doesn't help. 
I already deinstalled, downloaded the newest release again and reinstalled with the same problem. Maybe there is some configuration file still somewhere that cauese this, but I woudn't know where.

I had problems with autoupdates so I started the league on friday with an older version where this problem did not occure. But I had to update to use it since the querrys didn't work. After the update to the new version (uninstalled the old one and installed 8.2) it stopped working for me.

**To Reproduce**
Start POE and POE Overlay and press F5 in town. Nothing happens.

**Expected behavior**
Pressing the configured hotkey (or default) for i.e. the hideout command should paste the /hideout command to chat.

**Screenshots**
None, since nothing happens.

## 🌍  Your Environment

- OS: Windows 10 Professional 64 bit.
- Version: 8.2.0 full installation.
- PoE: standalone client, current 3.15 patch hotfix.

**Comment by kirillp** [comment] 2021-07-26 18:49
Same issue

**Comment by Aggnog** [comment] 2021-07-27 02:00
Same, since 0.8.2.

**Comment by HankTheDrunk** [comment] 2021-07-27 05:02
same problem

OS: Windows 7 Professional 64 bit
Version: 8.2.0 Portable **&** 8.3.0 Portable
PoE: standalone client, current 3.15 patch hotfix.

**Comment by Saladino** [comment] 2021-07-27 08:42
Also normal hotkeys like searching items and opening the wiki work fine, only the ones configured in the settings menu "Commands" don't work.

**Comment by WhiteFang5** [comment] 2021-07-27 13:12
Thank you for reporting this issue. The cause of the bug has been found and a fix will be shipped with the next release.

**Comment by WhiteFang5** [comment] 2021-07-30 05:31
This bug got fixed in v0.8.4

**Closed by WhiteFang5** 2021-07-30 05:31 UTC
Labels: bug
