### ISSUE TITLE
Not finding any results for rings with evasion

### ISSUE THREAD

**Issue by Reithan** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#147] opened 2020-09-30 05:00 UTC
# 🐞 bug report

**Describe the bug**
When searching for rings with evasion mods, none are found

**Screenshots**
![image](https://user-images.githubusercontent.com/7475701/94644791-17f63880-029f-11eb-89ca-3779fac9b4f8.png)

## 🌍  Your Environment

- OS: Win10 x64
- Version: 0.7.3
- PoE: Steam

**Comment by Reithan** [comment] 2020-09-30 18:02
This also seems to affect flat armour on belts

**Comment by WhiteFang5** [comment] 2020-10-02 06:22
This seems to be a duplicate of #138 ; which has been fixed in v0.7.4

**Closed by WhiteFang5** 2020-10-02 06:22 UTC
Labels: bug
